language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - TEST_DIR=crypto-hashes
script: cd $TEST_DIR && cargo build --verbose && cargo test --verbose
